### ISSUE TITLE
GCC / Clang

### ISSUE THREAD

**Issue by madmax2012** [fireice-uk/xmr-stak-nvidia#126]
Hi,
I did not get the compilation completed using clang as proposed by you (Ubuntu 17.04).
Using gcc-5 on the other hand does the trick
Maybe add this to your linux compilation guide

sudo update-alternatives --remove-all gcc 
sudo update-alternatives --remove-all g++
# Install GCC 5
sudo apt-get install gcc-5
sudo apt-get install g++-5
#Setup alternatives
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++
# Choose used version
sudo update-alternatives --config gcc
sudo update-alternatives --config g++
gcc -v

**Comment by sheepchen** [comment]
hello madmax2012, this trick didnt work for me.

I tryed it for 2 hours now and every way didnt work (gcc4, 5, 6, clang)
I have installed cuda_9.0.176_384.81_linux-run  NVIDIA-Linux-x86_64-384.90.run

Can you please tell me what I did wrong?


root@mpm01:/# sudo update-alternatives --remove-all gcc
update-alternatives: error: no alternatives for gcc
root@mpm01:/# sudo update-alternatives --remove-all g++
update-alternatives: error: no alternatives for g++
root@mpm01:/# sudo apt-get install gcc-5
Reading package lists... Done
Building dependency tree
Reading state information... Done
gcc-5 is already the newest version (5.4.1-8ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@mpm01:/# sudo apt-get install g++-5
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  libstdc++-5-dev
Suggested packages:
  g++-5-multilib gcc-5-doc libstdc++6-5-dbg libstdc++-5-doc
The following NEW packages will be installed:
  g++-5 libstdc++-5-dev
0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.
Need to get 9,863 kB of archives.
After this operation, 39.0 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://de.archive.ubuntu.com/ubuntu zesty/main amd64 libstdc++-5-dev amd64 5.4.1-8ubuntu1 [1,430 kB]
Get:2 http://de.archive.ubuntu.com/ubuntu zesty/universe amd64 g++-5 amd64 5.4.1-8ubuntu1 [8,434 kB]
Fetched 9,863 kB in 2s (4,104 kB/s)
Selecting previously unselected package libstdc++-5-dev:amd64.
(Reading database ... 142348 files and directories currently installed.)
Preparing to unpack .../libstdc++-5-dev_5.4.1-8ubuntu1_amd64.deb ...
Unpacking libstdc++-5-dev:amd64 (5.4.1-8ubuntu1) ...
Selecting previously unselected package g++-5.
Preparing to unpack .../g++-5_5.4.1-8ubuntu1_amd64.deb ...
Unpacking g++-5 (5.4.1-8ubuntu1) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up libstdc++-5-dev:amd64 (5.4.1-8ubuntu1) ...
Setting up g++-5 (5.4.1-8ubuntu1) ...
root@mpm01:/# sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 10
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20
sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
sudo update-alternatives --set cc /usr/bin/gcc
sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
sudo update-alternatives --set c++ /usr/bin/g++update-alternatives: using /usr/bin/gcc-5 to provide /usr/bin/gcc (gcc) in auto mode
root@mpm01:/# sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 10
update-alternatives: using /usr/bin/g++-5 to provide /usr/bin/g++ (g++) in auto mode
root@mpm01:/# sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 20
update-alternatives: using /usr/bin/gcc-6 to provide /usr/bin/gcc (gcc) in auto mode
root@mpm01:/# sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 20
update-alternatives: using /usr/bin/g++-6 to provide /usr/bin/g++ (g++) in auto mode
root@mpm01:/# sudo update-alternatives --install /usr/bin/cc cc /usr/bin/gcc 30
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/gcc because link group cc is broken
root@mpm01:/# sudo update-alternatives --set cc /usr/bin/gcc
root@mpm01:/# sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/g++ 30
update-alternatives: warning: forcing reinstallation of alternative /usr/bin/g++ because link group c++ is broken
root@mpm01:/# sudo update-alternatives --set c++ /usr/bin/g++
root@mpm01:/#
root@mpm01:/# sudo update-alternatives --config gcc
There are 2 choices for the alternative gcc (providing /usr/bin/gcc).

  Selection    Path            Priority   Status
------------------------------------------------------------
* 0            /usr/bin/gcc-6   20        auto mode
  1            /usr/bin/gcc-5   10        manual mode
  2            /usr/bin/gcc-6   20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/bin/gcc-5 to provide /usr/bin/gcc (gcc) in manual mode
root@mpm01:/#
root@mpm01:/# sudo update-alternatives --config g++
There are 2 choices for the alternative g++ (providing /usr/bin/g++).

  Selection    Path            Priority   Status
------------------------------------------------------------
* 0            /usr/bin/g++-6   20        auto mode
  1            /usr/bin/g++-5   10        manual mode
  2            /usr/bin/g++-6   20        manual mode

Press <enter> to keep the current choice[*], or type selection number: 1
update-alternatives: using /usr/bin/g++-5 to provide /usr/bin/g++ (g++) in manual mode
root@mpm01:/#
root@mpm01:/# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.1-8ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.1 20170304 (Ubuntu 5.4.1-8ubuntu1)
root@mpm01:/# cd /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0/
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# cmake .
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang
-- Check for working C compiler: /usr/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# make install
Scanning dependencies of target xmr-stak-nvidiaCuda
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
clang: error: cannot find libdevice for sm_20. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_30. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_35. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_37. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_50. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_52. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_60. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_61. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find libdevice for sm_62. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
clang: error: cannot find CUDA installation.  Provide its path via --cuda-path, or pass -nocudainc to build without CUDA includes.
CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0#

**Comment by psychocrypt** [comment]
You need to remove all tempory data from the last build. Or remove zmr-stak
and download the code again.
The previous used compiled is atored in the cmake cache file. That can be
the reason why clang is used even if the environment is changed.

Am 27.09.2017 9:43 Nachm. schrieb "sheepchen" <notifications@github.com>:

**Comment by sheepchen** [comment]
Hey, thanks.
I had to restart the whole server (Ubuntu Server 17.04). Now i had the next problem. It seems that Cuda 9 does not have the compute_20 lib.


root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# cmake .
-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang-4.0
-- Check for working C compiler: /usr/bin/clang-4.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-4.0
-- Check for working CXX compiler: /usr/bin/clang++-4.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda-9.0 (found suitable version "9.0", minimum required is "7.5")
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g")
-- Configuring done
-- Generating done
-- Build files have been written to: /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# make install
[  4%] Building NVCC (Device) object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o
nvcc fatal   : Unsupported gpu architecture 'compute_20'
CMake Error at xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o.Release.cmake:222 (message):
  Error generating
  /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0/CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/./xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o


CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:70: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/xmr-stak-nvidiaCuda_generated_cuda_extra.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0#

any suggestions?

**Comment by psychocrypt** [comment]
set your needed gpu architecture with a cmakw flag. -DCUDA_ARCH=xx

xx must be a number. https://developer.nvidia.com/cuda-gpus


Am 27.09.2017 10:42 Nachm. schrieb "sheepchen" <notifications@github.com>:

**Comment by sheepchen** [comment]
... step by step...

root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# cmake -DCUDA_ARCH="61;30" -DCUDA_COMPILER=clang .    # GTX 660 ti and GTX 1060

-- The C compiler identification is Clang 4.0.0
-- The CXX compiler identification is Clang 4.0.0
-- Check for working C compiler: /usr/bin/clang-4.0
-- Check for working C compiler: /usr/bin/clang-4.0 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++-4.0
-- Check for working CXX compiler: /usr/bin/clang++-4.0 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# make install
Scanning dependencies of target xmr-stak-nvidiaCuda
[  4%] Building CXX object CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o
clang: error: cannot find libdevice for sm_30. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
clang: error: cannot find libdevice for sm_61. Provide path to different CUDA installation via --cuda-path, or pass -nocudalib to build without linking with libdevice.
CMakeFiles/xmr-stak-nvidiaCuda.dir/build.make:62: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o' failed
make[2]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/nvcc_code/cuda_core.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/xmr-stak-nvidiaCuda.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-nvidiaCuda.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# env | grep CUDA; env | grep LD_LIBRARY_PATH
CUDA_BIN_PATH=/usr/local/cuda-9.0
LD_LIBRARY_PATH=:/usr/local/cuda-9.0/lib64
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0#

**Comment by psychocrypt** [comment]
You are still using clang. Please switch to g++. Clang is not Cuda9
compatible because cuda is currentl not released.

Am 27.09.2017 11:10 Nachm. schrieb "sheepchen" <notifications@github.com>:

**Comment by sheepchen** [comment]
ookay, my fault.. 

at first, thanks to your help by now..

and then:
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# export CC=/usr/bin/gcc-5
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# export CXX=/usr/bin/cpp-5
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# rm -r CMakeFiles/
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# cmake -DCUDA_ARCH="61;30" .    # GTX 660 ti and GTX 1060
-- The C compiler identification is GNU 5.4.1
-- The CXX compiler identification is GNU 5.4.1
-- Check for working C compiler: /usr/bin/gcc-5
-- Check for working C compiler: /usr/bin/gcc-5 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/gcc-5
-- Check for working CXX compiler: /usr/bin/gcc-5 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /work/tmp/xmr-stak-nvidia-1.1.1-1.4.0
root@mpm01:/work/tmp/xmr-stak-nvidia-1.1.1-1.4.0# make install >logging.log 2>&1

at first he build nicely.. but then.. 

[logging.log](https://github.com/fireice-uk/xmr-stak-nvidia/files/1338798/logging.log)

**Comment by sheepchen** [comment]
Hey,

now i have purged all compilation files (cpp, gcc, building_essentials, nvidia driver, cuda driver, etc.) and reinstalled them again.
With a little bit of tweakting i finally was able to build the xmr-stak-nvidia with the gcc-6 and cuda-9 on Ubuntu Server 17.04.

Now it doesnt run because of GPU 0 not found.
But this is likly because of insufficient power (# nvidia-smi) on my second (of 6) cards. [This is correct because i have only 1x6pin on it instead of 2].

When I am home again (at moment via ssh) I remove this card from the system and try again.
But the binary is runable, so it is build correctly.

Thanks psychocrypt for your patient help.
