### ISSUE TITLE
Can't build with amd+nvidia rig

### ISSUE THREAD

**Issue by omenius** [fireice-uk/xmr-stak-nvidia#161]
OS: Ubuntu 16.04.3 64bit
RIG: GTX960 + R9 290

I have both proprietary drivers installed, AMDGPU-PRO and the nvidia one, with CUDA support, both cards are reported and everything seems to work. However when I try to build from source, I get same errors that I've got with no nvidia gpu at all; "Unsupported gpu architecture 'compute_60'".

I already tried to use nvidia GPU as primary, just to build xmr-stak-nvidia, however my motherboard is very picky, it likes to go boot-loop easily and I have to reset my bios from backup time to time. This time my mobo choose that the GTX960 in PCI-E primary slot (the first one) is big no no, so I can't get my PC to boot with that setup. I think my mobo is slowly dying, I hope it has no pains :(

**Comment by psychocrypt** [comment]
You cuda version is 7.5 and sm_60 is not supported. (pascal gpus) please
set the architecture with CUDA_ARCH see README.md

Am 20.10.2017 23:08 schrieb "omenius" <notifications@github.com>:

OS: Ubuntu 16.04.3 64bit
RIG: GTX960 + R9 290

I have both proprietary drivers installed, AMDGPU-PRO and the nvidia one,
with CUDA support, both cards are reported and everything seems to work.
However when I try to build from source, I get same errors that I've got
with no nvidia gpu at all; "Unsupported gpu architecture 'compute_60'".

I already tried to use nvidia GPU as primary, just to build
xmr-stak-nvidia, however my motherboard is very picky, it likes to go
boot-loop easily and I have to reset my bios from backup time to time. This
time my mobo choose that the GTX960 in PCI-E primary slot (the first one)
is big no no, so I can't get my PC to boot with that setup. I think my mobo
is slowly dying, I hope it has no pains :(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fireice-uk/xmr-stak-nvidia/issues/161>, or mute the
thread

**Comment by omenius** [comment]
That helped.

Note to self: RTFM
