### ISSUE TITLE
Windows build size and performance

### ISSUE THREAD

**Issue by xmrig** [fireice-uk/xmr-stak-nvidia#84]
I built Windows version use this instruction [WINCOMPILE.md](https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/WINCOMPILE.md) without microhttpd and openssl and get 11 MB exe it close to 2x bigger that version from releases.

Also version from releases can use more aggressive settings and achieved better hashrate.
For example **NVIDIA 1050 Ti 4GB** suggested config:
```
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 64, "blocks" : 18,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],
```
Both versions 307 H/s

Old version:
```
"gpu_threads_conf" : [
  { "index" : 0,
    "threads" : 64, "blocks" : 24,
    "bfactor" : 6, "bsleep" :  25,
    "affine_to_cpu" : false,
  },
],
```
321 H/s work stable, blocks can increased to 26, but hashrate drops to 312.

New version crashed with same settings:
`[CUDA] Error gpu 0: <C:/monero/xmr-stak-nvidia/nvcc_code/cuda_extra.cu>:230`

Works only with `"blocks" : 22` 316 H/s.

Thank you.

**Comment by psychocrypt** [comment]
The current release is not build on the same way I described in the Wincompile documentation therefore the size differ.

What is the new and old version? Do you mean the last release and rhe current dev branch?

Please post the full error output for the error in line 230. The command line should also contain the reason.

**Comment by xmrig** [comment]
Old version: exe from releases.
New: current dev branch.

Stopped on these lines:
https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/nvcc_code/cuda_extra.cu#L229
https://github.com/fireice-uk/xmr-stak-nvidia/blob/dev/nvcc_code/cuda_extra.cu#L230

I remove checks, new version starts work on 321 H/s same as old version, but after few minutes, stop hashing (GPU still load at 100%) or give some impossibility hashrate, like 512000 H/s.

But old version magically can run on 321 H/s for days, shares accepted by pool, all looks good. Maybe some kind of undefined behavior I think your checks are good.

**Comment by psychocrypt** [comment]
I think the error is comming from to much memory use, see #1. It should help to reduce the number of threads or blocks.

Now for cuda experts: IMO The reason is that a kernel which is using lmem needs global memory at runtime. The amount of extra memory depends on the lmem size per thread for a kernel and the number of threads those can be active simultaneous on the gpu at the same time. It is not possible to calculate the needed extra memory before the kernel launch.

note to mayself: There are two ways to solve it, first way is reducing the used lmem and the second is to detect such a crash and auto fix the number of threads for the user during the run without a restart. Or stop the miner and let the user change the number of threads.

**Comment by psychocrypt** [comment]
@xmrig  The binary size of the release is smaller because @fireice-uk only compiled for the architectures `20,30,50,60` all other architectures will be compiled from the embedded ptx code at runtime.

**Comment by ghost** [comment]
my case.. solve.. !!!
 

with.,.,  this param... 




    "threads": [
        {
            "index": 0,
            "threads": 64,
            "blocks": 10,
            "bfactor": 6,
            "bsleep": 25,
            "affine_to_cpu": false
        }
